### ISSUE TITLE
yaml pipelines paths key uses incorrect terms for inclusion/exclusion and does not accept multiple items

### ISSUE THREAD

**Issue by drewmullen** [microsoft/azuredevopslabs#349]
to ignore updates to a README file, the documentation states to use the `exclude` param in the `paths` key. however names are swapped, `include` is the parameter that works. for branching, `include` and `exclude` are named / documented correctly

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#pr-trigger

documentation example: this does NOT exclude the README from PR builds
```yaml
pr:
  branches:
    include:
    - features/*
    exclude:
    - features/experimental/*
  paths:
    exclude:
    - README.md
```

what **actually** works is using `include`:
```yaml
pr:
  autoCancel: true
  branches:
   include: 
   - master
  paths:
   include:
   - README.md
```

**Comment by drewmullen** [comment]
a 2nd issue relating to this was discovered:
```yaml
paths:
   include:
    - README.md
```
this blocks the CI jobs to the README

```

```
pr:
  autoCancel: true
  branches:
   include: 
   - master
  paths:
   include:
   - README.md
   - Vagrantfile
```
this does not block CI jobs to `Vagrantfile`
