### ISSUE TITLE
CI Build Failing at Publish Task

### ISSUE THREAD

**Issue by palchak** [microsoft/azuredevopslabs#625]
I am following the link https://azuredevopslabs.com/labs/vstsextend/terraform/  and running the CI pipeline. This is my below YAML file 

```
trigger:
- master

pool:
  vmimage : windows-latest

variables:
   BuildConfiguration: 'release'
   buildPlatform: 'any cpu'
    
steps:
- task: DotNetCoreCLI@2
  displayName: Restore  
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.0.0'
  inputs:
    version: '2.0.0'


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    
- task: CopyFiles@2
  displayName: 'Copy Terraform files to artifacts'
  inputs:
    SourceFolder: Terraform
    TargetFolder: '$(build.artifactstagingdirectory)/Terraform'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
```

The build fails at Publish task with the error : 

C:\Program Files\dotnet\sdk\6.0.201\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: D:\a\1\s\src\PartsUnlimited.Models\config.json, D:\a\1\s\src\PartsUnlimitedWebsite\config.json. [D:\a\1\s\src\PartsUnlimitedWebsite\PartsUnlimitedWebsite.csproj]

Any idea how to fix this
![Build](https://user-images.githubusercontent.com/20683838/163623052-37baeff2-140d-48cd-badb-99aff1ec1acc.jpg)
