### ISSUE TITLE
Pipelines don't trigger on branch create when using paths include in trigger

### ISSUE THREAD

**Issue by rubenaster** [Microsoft/azuredevopslabs#643]
So we're following the monorepo approach and thus need some fine-grain pipeline triggers in our YAML files using paths includes.

For example like that:
```
trigger:
  batch: true
  branches:
    include:
    - main
    - refs/heads/release/demo02/v*
  paths:
    include:
    - src/Demo02
```

The problem is that pipelines don't trigger when you create a branch (which works with the branch includes) while you're using paths includes.

Is that a known issue and do you already have a solution for that on your roadmap?

If you only want to trigger one pipeline due to the creation of a branch then it's still okay if you need to trigger it manually. But if multiple pipelines should trigger then it gets messy if they don't trigger automatically.
