### ISSUE TITLE
CI/CD pipeline for Logic app (consumption) with parameterized connections

### ISSUE THREAD

**Issue by Nevinia210** [Microsoft/azuredevopslabs#692]
Hello,
I would like to ask if it is possible to deploy LogicApp to azure with parameterized connections,
currently im using task:
```
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: "Deploy ARM template"
                  inputs:
                    azureResourceManagerConnection: $(connectionName)
                    subscriptionName: $(subscriptionId)
                    resourceGroupName: $(resourceGroupName)
                    location: $(location)
                    csmFile: $(Pipeline.Workspace)/armtemplate/**/workflow.json
                    csmParametersFile: $(Pipeline.Workspace)/armtemplate/**/parameters.json
                    deploymentMode: "Incremental"
                    overrideParameters: -subscriptionId $(subscriptionId) -resourceGroupName $(resourceGroupName) -location $(locationParameter)
```
this task deploy my logic app correctly, but there are no parameters
my workflow.json looks like this:
![image](https://github.com/microsoft/azuredevopslabs/assets/42325625/ac829b4e-130f-4d84-a17a-e03a099fbd96)

Im getting this kind of error:
#[error]LinkedAuthorizationFailed: The client has permission to perform action 'Microsoft.Web/connections/join/action' on scope '/subscriptions/xxxxx/resourcegroups/xxxx/providers/Microsoft.Logic/workflows/LogicAppTestDeploy2', however the linked subscription '[parameters('subscriptionId')]' was not found. 

Am i doing something wrong? or is it even possible to make connections parameterized?

thank you for your answers
